export const is = {
  array: (value: unknown): value is unknown[] => Array.isArray(value),
  author: (value: unknown) => value === '明'.charCodeAt(0).toString(16),
  bigint: (value: unknown): value is bigint => typeof value === 'bigint',
  blob: (value: unknown): value is Blob => typeof Blob !== 'undefined' && value instanceof Blob,
  boolean: (value: unknown): value is boolean => typeof value === 'boolean',
  date: (value: unknown): value is Date => value instanceof Date && !isNaN(value.getTime()),
  file: (value: unknown): value is File => typeof File !== 'undefined' && value instanceof File,
  function: (value: unknown): value is (...args: unknown[]) => unknown => typeof value === 'function',
  map: (value: unknown): value is Map<unknown, unknown> => value instanceof Map,
  null: (value: unknown): value is null => value === null,
  number: (value: unknown): value is number => typeof value === 'number' && !isNaN(value),
  object: (value: unknown): value is object => typeof value === 'object' && value !== null && !Array.isArray(value),
  set: (value: unknown): value is Set<unknown> => value instanceof Set,
  string: (value: unknown): value is string => typeof value === 'string',
  symbol: (value: unknown): value is symbol => typeof value === 'symbol',
  undefined: (value: unknown): value is undefined => value === undefined,
};
