export const is = {
  array: (value: unknown) => Array.isArray(value),
  author: (value: unknown) => value === '明'.charCodeAt(0).toString(16),
  bigint: (value: unknown) => Object.prototype.toString.call(value) === '[object BigInt]',
  boolean: (value: unknown) => Object.prototype.toString.call(value) === '[object Boolean]',
  date: (value: unknown) => Object.prototype.toString.call(value) === '[object Date]',
  function: (value: unknown) => Object.prototype.toString.call(value) === '[object Function]',
  map: (value: unknown) => Object.prototype.toString.call(value) === '[object Map]',
  null: (value: unknown) => value === null,
  number: (value: unknown) => Object.prototype.toString.call(value) === '[object Number]',
  object: (value: unknown) => Object.prototype.toString.call(value) === '[object Object]',
  set: (value: unknown) => Object.prototype.toString.call(value) === '[object Set]',
  string: (value: unknown) => Object.prototype.toString.call(value) === '[object String]',
  symbol: (value: unknown) => Object.prototype.toString.call(value) === '[object Symbol]',
  undefined: (value: unknown) => value === void 0,
};
